// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'details': string;
  'image': string;
  'imageContainer': string;
  'message': string;
  'stackTrace': string;
  'version': string;
}
export const cssExports: CssExports;
export default cssExports;
